<a href="https://colab.research.google.com/github/AmeerHamza111/AIPND/blob/master/starting%20Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

### Steps in building your first ANN

*   Data Preprocessing
*   Add Input layer
*   Random w init
*   Add Hidden Layers
*   Select Optimizer, Loss, and Performance Metrics
*   Comiler and model
*   Use model.fit to tain the model
*   Evaluate the model
*   Adjust Optimization parameters or model if needed





In [0]:
print(tf.__version__)

2.2.0-rc2


In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [0]:
dataset = pd.read_csv('/Customer_Churn_Modelling.csv')

In [0]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
x = dataset.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis= 1)
y = dataset['Exited']

In [15]:
x.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [16]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

**In order to convert the sting values of 'Gender' and 'Geography' into a numaricacl value we use *Incode*.** 


In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
label1 = LabelEncoder()
x['Geography'] = label1.fit_transform(x['Geography'])

In [25]:
x.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [0]:
label2 = LabelEncoder()
x['Gender'] = label2.fit_transform(x['Gender'])

In [30]:
x.head(10)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10
5          645          2       1  ...          1               0        149756.71
6          822          0       1  ...          1               1         10062.80
7          376          1       0  ...          1               0        119346.88
8          501          0       1  ...          0               1         74940.50
9          684          0       1  ...          1               1         71725.73

[10 rows x 10 columns]

### These string values should not be innterpreted as numarical values, the string values should be treated as catagorical values 

In [32]:
#  HotEncoding 
x = pd.get_dummies(x, drop_first=True, columns=['Geography'])
x.head()

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1

[5 rows x 11 columns]

### Feature Standardization

In [0]:
from sklearn.preprocessing import  StandardScaler

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0, stratify = y)

In [0]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [39]:
# Checking data if it standardized 
x_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

### Building ANN


In [0]:
# Building a sequential model
model = Sequential()
# Adding input layer
model.add(Dense(x.shape[1], activation='relu', input_dim= x.shape[1]))
# Adding ssingle hidden layers
model.add(Dense(128, activation='relu'))
# adding output layer
model.add(Dense(1, activation='sigmoid'))


In [44]:
x.shape[1]

11

In [0]:
# Bach gradient decent model is not used , 'adam' is used
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [50]:
model.fit(x_train, y_train.to_numpy(), batch_size=10, epochs=10, verbose=1)

Epoch 1/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3131 - accuracy: 0.8671
Epoch 2/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3126 - accuracy: 0.8684
Epoch 3/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3111 - accuracy: 0.8677
Epoch 4/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3109 - accuracy: 0.8677
Epoch 5/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3107 - accuracy: 0.8691
Epoch 6/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3102 - accuracy: 0.8665
Epoch 7/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3085 - accuracy: 0.8692
Epoch 8/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3087 - accuracy: 0.8716
Epoch 9/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3076 - accuracy: 0.8671
Epoch 10/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3080 - accuracy: 0.8677

In [0]:
y_pred = np.argmax(model.predict(x_test), axis=1)


In [79]:
y_pred 

array([0, 0, 0, ..., 0, 0, 0])

In [80]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [81]:
model.evaluate(x_test, y_test.to_numpy())

63/63 [==============================] - 0s 1ms/step - loss: 110134.3125 - accuracy: 0.2035


[110134.3125, 0.20350000262260437]

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [83]:
accuracy_score(y_test, y_pred)

0.7965

In [84]:
confusion_matrix(y_test, y_pred)

array([[1593,    0],
       [ 407,    0]])